<?php
/**
 * SB GO Theme Functions and definitions
 *
 * @package SB_GO_Theme
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

define('SB_GO_VERSION', '1.1.0');
define('SB_GO_THEME_DIR', get_template_directory());
define('SB_GO_THEME_URI', get_template_directory_uri());

/**
 * Sets up theme defaults and registers support for various WordPress & Elementor features.
 */
function sb_go_theme_setup() {
    // Add default posts and comments RSS feed links to head.
    add_theme_support('automatic-feed-links');

    // Let WordPress manage the document title.
    add_theme_support('title-tag');

    // Enable support for Post Thumbnails on posts and pages.
    add_theme_support('post-thumbnails');

    // Switch default core markup to output valid HTML5.
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ));

    // Support custom logo
    add_theme_support('custom-logo', array(
        'height'      => 80,
        'width'       => 80,
        'flex-height' => true,
        'flex-width'  => true,
    ));

    // Register Navigation Menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', 'sb-go-theme'),
        'footer'  => __('Footer Menu', 'sb-go-theme'),
    ));

    // Full Elementor & Elementor Free Support
    add_theme_support('elementor');
    add_theme_support('align-wide');
    add_theme_support('responsive-embeds');
}
add_action('after_setup_theme', 'sb_go_theme_setup');

/**
 * Register Elementor Theme Locations (Header, Footer, Single)
 * Compatible with Elementor Pro and Elementor Header & Footer Builder.
 */
function sb_go_register_elementor_locations($elementor_theme_manager) {
    if (method_exists($elementor_theme_manager, 'register_all_core_location')) {
        $elementor_theme_manager->register_all_core_location();
    }
}
add_action('elementor/theme/register_locations', 'sb_go_register_elementor_locations');

/**
 * Check if the current page is being edited or viewed with Elementor.
 *
 * @param int|null $post_id
 * @return bool
 */
function sb_go_is_elementor($post_id = null) {
    if (!$post_id) {
        $post_id = get_the_ID();
    }

    // Check Elementor edit or preview mode
    if (did_action('elementor/loaded')) {
        if (\Elementor\Plugin::$instance->editor->is_edit_mode()) {
            return true;
        }
        if (\Elementor\Plugin::$instance->preview->is_preview_mode()) {
            return true;
        }
        if ($post_id && \Elementor\Plugin::$instance->db->is_built_with_elementor($post_id)) {
            return true;
        }
    }

    // Fallback meta check for Elementor builder mode
    if ($post_id) {
        $mode = get_post_meta($post_id, '_elementor_edit_mode', true);
        if ('builder' === $mode) {
            return true;
        }
    }

    return false;
}

/**
 * Check if Elementor editor is currently open.
 *
 * @return bool
 */
function sb_go_is_elementor_editor() {
    if (did_action('elementor/loaded')) {
        return \Elementor\Plugin::$instance->editor->is_edit_mode() 
            || \Elementor\Plugin::$instance->preview->is_preview_mode();
    }
    return isset($_GET['elementor-preview']);
}

/**
 * Enqueue scripts and styles generated by Vite and standard WordPress styles.
 */
function sb_go_enqueue_scripts() {
    // Enqueue style.css for WordPress theme validation
    wp_enqueue_style('sb-go-style', get_stylesheet_uri(), array(), SB_GO_VERSION);

    // Look for Vite manifest
    $manifest_paths = array(
        SB_GO_THEME_DIR . '/dist/.vite/manifest.json',
        SB_GO_THEME_DIR . '/dist/manifest.json',
    );

    $manifest = null;
    foreach ($manifest_paths as $path) {
        if (file_exists($path)) {
            $content = file_get_contents($path);
            $manifest = json_decode($content, true);
            break;
        }
    }

    // Always enqueue Tailwind CSS for global utility styles
    if ($manifest) {
        foreach ($manifest as $entry_key => $entry) {
            if (!empty($entry['isEntry']) && !empty($entry['css'])) {
                foreach ($entry['css'] as $i => $css_file) {
                    wp_enqueue_style(
                        'sb-go-vite-css-' . $i,
                        SB_GO_THEME_URI . '/dist/' . $css_file,
                        array(),
                        SB_GO_VERSION
                    );
                }
            }
        }
    } else {
        $assets_dir = SB_GO_THEME_DIR . '/dist/assets';
        if (is_dir($assets_dir)) {
            $files = scandir($assets_dir);
            foreach ($files as $file) {
                if (pathinfo($file, PATHINFO_EXTENSION) === 'css') {
                    wp_enqueue_style(
                        'sb-go-asset-css-' . sanitize_title($file),
                        SB_GO_THEME_URI . '/dist/assets/' . $file,
                        array(),
                        SB_GO_VERSION
                    );
                }
            }
        }
    }

    // Only enqueue the React single-page bundle if Elementor editor is NOT active
    // This allows Elementor Free's visual drag-and-drop editor canvas to work cleanly without conflicts!
    if (!sb_go_is_elementor_editor()) {
        if ($manifest) {
            foreach ($manifest as $entry_key => $entry) {
                if (!empty($entry['isEntry']) && !empty($entry['file'])) {
                    wp_enqueue_script(
                        'sb-go-vite-app',
                        SB_GO_THEME_URI . '/dist/' . $entry['file'],
                        array(),
                        SB_GO_VERSION,
                        true
                    );
                }
            }
        } else {
            $assets_dir = SB_GO_THEME_DIR . '/dist/assets';
            if (is_dir($assets_dir)) {
                $files = scandir($assets_dir);
                foreach ($files as $file) {
                    if (pathinfo($file, PATHINFO_EXTENSION) === 'js') {
                        wp_enqueue_script(
                            'sb-go-asset-js-' . sanitize_title($file),
                            SB_GO_THEME_URI . '/dist/assets/' . $file,
                            array(),
                            SB_GO_VERSION,
                            true
                        );
                    }
                }
            }
        }

        // Expose dynamic WordPress site context to the React application
        wp_localize_script('sb-go-vite-app', 'sbGoWpData', array(
            'siteUrl'     => esc_url_raw(home_url('/')),
            'themeUrl'    => esc_url_raw(SB_GO_THEME_URI),
            'restUrl'     => esc_url_raw(rest_url()),
            'nonce'       => wp_create_nonce('wp_rest'),
            'siteName'    => get_bloginfo('name'),
            'isElementor' => sb_go_is_elementor(),
        ));
    }
}
add_action('wp_enqueue_scripts', 'sb_go_enqueue_scripts');

/**
 * Add type="module" attribute to the Vite script tag.
 */
function sb_go_script_type_module($tag, $handle, $src) {
    if (strpos($handle, 'sb-go-vite-app') !== false || strpos($handle, 'sb-go-asset-js') !== false) {
        return '<script type="module" src="' . esc_url($src) . '"></script>';
    }
    return $tag;
}
add_filter('script_loader_tag', 'sb_go_script_type_module', 10, 3);
